### ISSUE TITLE
indivisuallyの指定はfunctionの外に必要なのか内側に必要なのか両方なのかわからない

### ISSUE THREAD

**Issue by hirobel** [hirobel/sls-deploy-from-artifact#1]
### 背景

indivisuallyという指定をすると、function毎に別々なartifactを指定できるようだ。ドキュメントによると。
ただ、それをpackageのセクションに指定すればよいのか、functionのセクションに指定すればよいのか、両方なのかが読み取れていない

### 参考
* https://serverless.com/framework/docs/providers/aws/guide/packaging#individual-function-packages

**Comment by hirobel** [comment]
以下の4パターンでserverless.ymlを用意して比較してみるのが良さそう

pattern_name | package.individually | function.package.individually
-- | -- | --
02_01_from-artifact-oneside_1 | TRUE | TRUE
02_02_from-artifact-oneside_2 | TRUE | FALSE
02_03_from-artifact-oneside_3 | FALSE | TRUE
02_04_from-artifact-oneside_4 | FALSE | FALSE

**Comment by hirobel** [comment]
s3に2つのpackageを用意して、次のようにserverless.ymlを設定して、indivisuallyの設定を↑のパターン分用意して試してみたけど、全部同じ結果だった。
なぜだろう・・

### serverless.yml
```
service: try-sls-deploy-from-artifact021

provider:
  name: aws
  runtime: java8
  stage: dev
  region: ap-northeast-1

package:
  artifact: https://s3.amazonaws.com/hirobel-sandbox/sls-deploy-from-artifact/hello_v0.0.2.zip
  individually: true

functions:
  hello:
    handler: com.serverless.Handler
    package:
      individually: false
      artifact: https://s3.amazonaws.com/hirobel-sandbox/sls-deploy-from-artifact/hello_v0.0.1.zip

  goodbye:
    handler: com.serverless.HandlerGoodBye
```
```
service: try-sls-deploy-from-artifact022
︙
package:
  artifact: https://s3.amazonaws.com/hirobel-sandbox/sls-deploy-from-artifact/hello_v0.0.2.zip
  individually: true
︙
functions:
  hello:
    package:
      individually: true
      artifact: https://s3.amazonaws.com/hirobel-sandbox/sls-deploy-from-artifact/hello_v0.0.1.zip
︙
```
```
service: try-sls-deploy-from-artifact023
︙
package:
  artifact: https://s3.amazonaws.com/hirobel-sandbox/sls-deploy-from-artifact/hello_v0.0.2.zip
  individually: false
︙
functions:
  hello:
    package:
      individually: true
      artifact: https://s3.amazonaws.com/hirobel-sandbox/sls-deploy-from-artifact/hello_v0.0.1.zip
︙
```
```
service: try-sls-deploy-from-artifact024
︙
package:
  artifact: https://s3.amazonaws.com/hirobel-sandbox/sls-deploy-from-artifact/hello_v0.0.2.zip
  individually: false
︙
functions:
  hello:
    package:
      individually: false
      artifact: https://s3.amazonaws.com/hirobel-sandbox/sls-deploy-from-artifact/hello_v0.0.1.zip
︙
```
### package
v0.0.1のpackageのhash | t5z4vo09Wf+bFEfbZ1OKpLHvP6AcPLGQOP4hRPnVZ1M=
-- | --
v0.0.2のpackageのhash | LMf+ZDe31ZcfPKQOiZ//ahvuiZkv6+/VrqQ2aFJn/ko=

### test pattern
pattern_name | package.individually | function.package.individually | hello関数のhash | goodbye関数のhash
-- | -- | -- | -- | --
02_01_from-artifact-oneside_1 | TRUE | TRUE | t5z4vo09Wf+bFEfbZ1OKpLHvP6AcPLGQOP4hRPnVZ1M= | LMf+ZDe31ZcfPKQOiZ//ahvuiZkv6+/VrqQ2aFJn/ko=
02_02_from-artifact-oneside_2 | TRUE | FALSE | t5z4vo09Wf+bFEfbZ1OKpLHvP6AcPLGQOP4hRPnVZ1M= | LMf+ZDe31ZcfPKQOiZ//ahvuiZkv6+/VrqQ2aFJn/ko=
02_03_from-artifact-oneside_3 | FALSE | TRUE | t5z4vo09Wf+bFEfbZ1OKpLHvP6AcPLGQOP4hRPnVZ1M= | LMf+ZDe31ZcfPKQOiZ//ahvuiZkv6+/VrqQ2aFJn/ko=
02_04_from-artifact-oneside_4 | FALSE | FALSE | t5z4vo09Wf+bFEfbZ1OKpLHvP6AcPLGQOP4hRPnVZ1M= | LMf+ZDe31ZcfPKQOiZ//ahvuiZkv6+/VrqQ2aFJn/ko=

### 検証コード
https://github.com/hirobel/sls-deploy-from-artifact/tree/feature/use-indivisually-setting
