### ISSUE TITLE
artifactにS3のjarを指定してデプロイできない

### ISSUE THREAD

**Issue by hirobel** [hirobel/sls-deploy-from-artifact#2]

**Comment by hirobel** [comment]
### 背景
以下の記事によると、artifactにs3上へ配置したアーカイブを指定して、lambdaにデプロイ出来るようである
https://serverless.com/framework/docs/providers/aws/guide/packaging#artifacts-hosted-on-s3

ただ、記事に合わせて指定してみたところエラーになってしまう

### 状況

> 指定方法
```
service: try-sls-deploy-from-artifact

provider:
  name: aws
  runtime: java8
  stage: dev
  region: ap-northeast-1

package:
  # artifact: https://s3.amazonaws.com/hirobel-sandbox/try-sls-deploy-from-artifact.jar

functions:
  hello:
    handler: com.serverless.Handler
```

> 結果1：パス形式で指定した場合
```
AccessDenied: Access Denied
```

> 結果2：仮想ホスト形式で指定した場合
```
Error: ENOENT: no such file or directory, open 'https://hirobel-sandbox.s3-ap-northeast-1.amazonaws.com/try-sls-deploy-from-artifact.jar'
```

> 結果3：仮想ホスト形式から、試しにリージョンを削って指定してみた場合
```
Error: ENOENT: no such file or directory, open 'https://hirobel-sandbox.s3.amazonaws.com/try-sls-deploy-from-artifact.jar'
```
